### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by jitash** [matrix-org/matrix-rust-components-swift#11]
I want to use this library as a dependency in my kmm project using CocoaPods, but I don't know how to publish it. Can someone please help me?

**Comment by stefanceriu** [comment]
I'm sorry but we don't have the bandwidth to handle publishing to cocoapods. What I can suggest is that you directly use the  xcframeworks published here https://github.com/matrix-org/matrix-rust-components-swift/releases

**Comment by jitash** [comment]
Well, thank you for your reply.
