### ISSUE TITLE
Getting Started mentions it isn't yet async while the code is async now?

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-rust-components-swift#13]
**Describe the bug**

The docs/Getting Started.md still has this:

> In its current state, many of the calls to the SDK will block the thread that they're called on. You can determine this by looking for functions that use RUNTIME.block_on in their implementation. This is temporary and will be addressed in the future via https://github.com/mozilla/uniffi-rs/pull/1409.

But searching the code for block_on yields no code results. Am I correctly assuming this is not true anymore? :)

**Comment by jplatte** [comment]
The bindings/matrix-sdk-ffi directory in the SDK repo contains the Rust bindings code, which still does `block_on` in many places. There's been some movement to fix async problems in UniFFI lately, and I think we'll be able to use it consistently everywhere in a few weeks.

**Comment by MTRNord** [comment]
Ah ok :) that makes sense then! Thanks!
