### ISSUE TITLE
Usage of Swift Async

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-rust-components-swift#3]
Together with https://github.com/matrix-org/matrix-rust-components-swift/issues/2, and swift async, any downstream project (such as element-x-ios) can benefit from the async-ness of library, allowing for smoother experiences (with apple components such as swiftUI, which has better responsiveness then)

This can be done in either of two ways;
- Transform an upstream ffi bridge project (either uniffi or swift-bridge) to support async wholly
- Provide swift shims in this library, which convert all async calls into “continuations” (swift-bridge does this internally already) that then get scheduled and called internally

**Comment by poljar** [comment]
`uniffi` nowadays supports async Swift, support for this was recently merged in https://github.com/matrix-org/matrix-rust-sdk/pull/1661. It's not yet clear if the approach is bug-free, but I think we can close this issue.
